"""Encrypt email and add email_hash to User model

Revision ID: 5cf7c3c4ce41
Revises: 7f9c4c77ee15
Create Date: 2025-08-27 17:32:02.268585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf7c3c4ce41'
down_revision: Union[str, Sequence[str], None] = '7f9c4c77ee15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.drop_column('users', 'email_hash')
    # ### end Alembic commands ###
