"""add goal to roadmap

Revision ID: 771e9b980b3d
Revises: 5cf7c3c4ce41
Create Date: 2025-09-03 16:58:42.287599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771e9b980b3d'
down_revision: Union[str, Sequence[str], None] = '5cf7c3c4ce41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('goal', sa.Text(), nullable=True))
    op.add_column('roadmaps', sa.Column('ai_generated_content', sa.Text(), nullable=True))
    op.create_index(op.f('ix_roadmaps_goal'), 'roadmaps', ['goal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmaps_goal'), table_name='roadmaps')
    op.drop_column('roadmaps', 'ai_generated_content')
    op.drop_column('roadmaps', 'goal')
    # ### end Alembic commands ###
