"""Add user_id to AIResponse model

Revision ID: 7fb31ec9b0f6
Revises: 92ee61e9c102
Create Date: 2025-08-23 00:12:58.145377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb31ec9b0f6'
down_revision: Union[str, Sequence[str], None] = '92ee61e9c102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_responses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE ai_responses SET user_id = 1 WHERE user_id IS NULL")
    op.alter_column('ai_responses', 'user_id',
               existing_type=sa.Integer(),
               nullable=False,
               existing_nullable=True)
    op.create_foreign_key(None, 'ai_responses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_responses', type_='foreignkey')
    op.drop_column('ai_responses', 'user_id')
    # ### end Alembic commands ###
