"""Make skill_id nullable in AIResponse model

Revision ID: 92ee61e9c102
Revises: 4dd5114b9817
Create Date: 2025-08-23 00:03:05.336819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ee61e9c102'
down_revision: Union[str, Sequence[str], None] = '4dd5114b9817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_responses', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_responses', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
